{
 "title": "Assets",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Assets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Good items count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DeviceData",
     "query": "SELECT count(\"ITEM_COUNT_GOOD\") FROM \"DeviceData\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "ITEM_COUNT_BAD" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "ITEM_COUNT_GOOD" ], "type": "field" }
      ],
      [
       { "params": [ "STATUS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bad items count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DeviceData",
     "query": "SELECT count(\"ITEM_COUNT_BAD\") FROM \"DeviceData\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "ITEM_COUNT_BAD" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "ITEM_COUNT_GOOD" ], "type": "field" }
      ],
      [
       { "params": [ "STATUS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Good and bad assets comparison",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DeviceData",
     "select": [
      [
       { "params": [ "ITEM_COUNT_GOOD" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Good assets" ], "type": "alias" }
      ],
      [
       { "params": [ "ITEM_COUNT_BAD" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bad assets" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Status over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DeviceData",
     "query": "SELECT mean(\"STATUS\") as Status FROM \"DeviceData\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "STATUS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Good assets over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DeviceData",
     "query": "SELECT mean(\"ITEM_COUNT_GOOD\") AS \"Good assets\" FROM \"DeviceData\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ITEM_COUNT_GOOD" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Good assets" ], "type": "alias" }
      ],
      [
       { "params": [ "ITEM_COUNT_BAD" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bad assets" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Good and bad assets comparison",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DeviceData",
     "query": "SELECT mean(\"ITEM_COUNT_BAD\") AS \"Bad assets\" FROM \"DeviceData\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ITEM_COUNT_GOOD" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Good assets" ], "type": "alias" }
      ],
      [
       { "params": [ "ITEM_COUNT_BAD" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bad assets" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}